# Generated by Django 4.1.5 on 2023-01-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("olaviat", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
