# Generated by Django 4.1.5 on 2023-01-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("low_quality_image", models.ImageField(upload_to="uploads/")),
                ("high_quality_image", models.ImageField(upload_to="uploads/")),
            ],
        ),
        migrations.AddField(
            model_name="gallery",
            name="cover_image",
            field=models.ImageField(default=0, upload_to="uploads/"),
            preserve_default=False,
        ),
    ]
