# Generated by Django 4.1.5 on 2023-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0002_photo_gallery_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="cover_image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="high_quality_image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="low_quality_image",
            field=models.ImageField(upload_to=""),
        ),
    ]
