# Generated by Django 4.1.5 on 2023-01-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_gallery_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="photos.gallery",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photo",
            name="olaviat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
