# Generated by Django 4.1.5 on 2023-01-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0004_photo_category_photo_olaviat"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="description",
            field=models.CharField(default="man yen parandam", max_length=200),
            preserve_default=False,
        ),
    ]
